### ISSUE TITLE
Quickstart Webpack Compile Error

### ISSUE THREAD

**Issue by acorer** [stasson/vue-mdc-adapter#264] opened 2018-02-13 06:43 UTC
Steps to reproduce
Follow the guide at https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started

**# Quick Start**

**## Vue CLI Webpack**
```
npm install -g vue-cli

vue init stasson/vue-mdc-adapter-webpack my-project

cd my-project

npm install

npm run dev

```
**Gets the following Error:**

ERROR  Failed to compile with 1 errors

 error  in ./src/theme.scss

Module build failed: 
    @include mdc-states(secondary);
            ^
      No mixin named mdc-states

Backtrace:
	node_modules/vue-mdc-adapter/dist/button/styles.scss:7
      in /home/acorer/repos/vda-quickstart-webpack/node_modules/vue-mdc-adapter/dist/button/styles.scss (line 7, column 14)

 @ ./src/theme.scss 4:14-191 13:3-17:5 14:22-199
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by griest024** [comment] 2018-02-13 07:24
Probable duplicate of #237

**Comment by acorer** [comment] 2018-02-13 07:45
Looks like updating material-components-web to 0.29.0 solved the issue.

However shouldn't this be applied to the template package.json itself?

The quick start needs to be working.

**Comment by griest024** [comment] 2018-02-13 17:14
Yup I agree. Actually 0.30 is the newest MDC web version

**Comment by stasson** [comment] 2018-02-13 17:14
mmmh,  guess I need to find a way to properly get material-web-components installed

**Comment by pgbross** [comment] 2018-03-21 12:15
OS: Fedora 27

I just tried the reproduce steps listed above and it installs and compiles correctly.

Has this issue gone away with more recent versions of the `stasson/vue-mdc-adapter-webpack` template?

**Closed** 2018-08-07 22:12 UTC
Labels: P2
