### ISSUE TITLE
[Bug] Ripple effect is not correctly centered on mdc-radio component inside mdc-dialog

### ISSUE THREAD

**Issue by SirAuron** [stasson/vue-mdc-adapter#401] opened 2018-04-18 15:34 UTC
### What vue-mdc-adapter Version are you using?

V 0.14.0
But tested also in V 0.13.5

### What browser(s) is this bug affecting?

Tested on:
Chrome 65
Firefox 59
Edge 41 (HTML Version 16)

### What OS are you using?

Windows 10, Android 5.1.1

### What are the steps to reproduce the bug?

- Create a mdc-dialog component with scrollable option set to true
- Inside its content create one or more mdc-radio component
- Then click on the mdc-radio round button

### What is the expected behavior?

The ripple effect on the round button of the radio element  should be centered.

### What is the actual behavior?

Clicking the element the ripple effect and its related _before element_ are not centered.

### Any other information you believe would be useful?

I spent quite some time investigating before finding out that when the mdc-radio is contained _inside_ the mdc-dialog, the ripple variables are calculated and set differently than when the same element is _outside_ the dialog. For example:

```
// Incorrect element style set on element inside the dialog
style="--mdc-ripple-fg-size:19.2px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:6px; --mdc-ripple-top:6px;"

// Correct element style set on element outside dialog
style="--mdc-ripple-fg-size:24px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:8px; --mdc-ripple-top:8px;"
```

When referencing the _before element_, I'm talking about this one:
```
.mdc-radio.mdc-ripple-upgraded::before, .mdc-radio.mdc-ripple-upgraded::after {
    top: var(--mdc-ripple-top, calc(50% - 50%));
    left: var(--mdc-ripple-left, calc(50% - 50%));
    width: var(--mdc-ripple-fg-size, 100%);
    height: var(--mdc-ripple-fg-size, 100%);
}
```

I'm not sure if this issue should be here or directly on Material components web repository, since it is mostly a style calculation.

**Comment by pgbross** [comment] 2018-04-23 11:11
Thank you for reporting this issue. After a quick look at the behaviour it seems like it is related to when the ripple calculation is made. The mdc-radio component adds the ripple as part of its initialisation, but when contained in a dialog it is initialised "off-screen" as the dialog is not visible initially. The layout of the off-screen dialog is smaller than it appears when shown. I am not sure if this is the root cause of the problem but I note that the underlying `mdc-ripple` is being modified for the next release of `material-web-components` (MWC) (presumably v0.35.0) to calculate its layout on activation.

When the next release of MWC happens and the relevant updates are made to `vue-mdc-adapter` it will be interesting to see if this issue is resolved.

**Comment by SirAuron** [comment] 2018-04-30 13:55
Just checked the state of this issue after updating vue-mdc-adapter from v0.14.0 to v0.15.0.

From my tests, it seems that with the update of MWC this issue has been solved, as @pgbross said in [his comment](https://github.com/stasson/vue-mdc-adapter/issues/401#issuecomment-383539040). 

If your tests give the same results, we can close this issue.

**Comment by stasson** [comment] 2018-05-01 09:07
thxs !

**Closed by stasson** 2018-05-01 09:07 UTC
Labels: bug
